### ISSUE TITLE
How do we stop the perf-test connection with RabbitMQ in cloud foundry?

### ISSUE THREAD

**Issue by junnyea** [rabbitmq/rabbitmq-perf-test-for-cf#11]
I run a **perf-test-app** in cloud foundry for 1 hour with the following args:
      JBP_CONFIG_JAVA_MAIN: >
        { arguments: "-x 1 -y 2" }

There were 2k connections created. 
However, when I stopped the app. I can still see the no of connections created increased. 
The connections only disappear after I deleted the **perf-test-app** from cloud foundry.

Does the above scenario appropriate?

**Comment by acogoluegnes** [comment]
With the arguments you're using, PerfTest should open 4 connections (1 for the producer, 2 for the consumers, 1 to configure the AMQP resources). Is it what you observed, at least at the beginning of the run?

PerfTest creates connections with a `perf-test-` prefix for the connection name, can you confirm the 2 K connections you see have this prefix?

The only thing I can think of with the information provided is a connection leak when PerfTest tries to reconnect because of a flaky network, but this is just guessing.

Please provide a way to reproduce or more information (server logs, PerfTest logs). If we go down this road, please move this to the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users). This issue will then be used to sum up our findings and actionable items, like a bug to fix. Thanks.

**Comment by junnyea** [comment]
I actually using the simplest argument to replicate the result

To reply your question
With the arguments you're using, PerfTest should open 4 connections (1 for the producer, 2 for the consumers, 1 to configure the AMQP resources). Is it what you observed, at least at the beginning of the run? 
**Answer : "YES"**

PerfTest creates connections with a perf-test- prefix for the connection name, can you confirm the 2 K connections you see have this prefix? 
**Answer: No**

I have noted the issue here https://groups.google.com/forum/#!topic/rabbitmq-users/Qa3wtoVi8P4
with attached 4k connections result.
